# Generated by Django 4.1.2 on 2022-10-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='price',
            new_name='real_price',
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='discount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
