# Generated by Django 4.1.2 on 2022-10-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_price_bookmodel_real_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
