# Generated by Django 4.1.2 on 2022-10-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_authormodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresmodel',
            name='cover',
            field=models.IntegerField(choices=[(1, 'Hard'), (0, 'Soft')]),
        ),
        migrations.AlterField(
            model_name='featuresmodel',
            name='paper_format',
            field=models.IntegerField(choices=[(1, 'A3'), (2, 'A4'), (3, 'A5')]),
        ),
    ]
